version: '3'
services:
  server:
    container_name: 'server-lpdg'
    build: ./docker/server
    volumes:
      - ./:/var/www/:rw,cached
    ports:
      - '${APACHE_PORT}:80'
    depends_on:
      - db
  db:
    container_name: 'database-lpdg'
    image: mysql:5.7
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
